# Generated by Django 3.1.3 on 2020-11-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
