# Generated by Django 3.1.3 on 2020-11-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201112_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
